services:
  - type: web
    name: spyhaz
    env: node
    plan: free
    buildCommand: "npm install --production=false && cd client && npm install --production=false && npm run build && cd ../server && npm install"
    startCommand: "cd server && npm start"
    envVars:
      - key: NODE_ENV
        value: production
